import util.queries.EagerQueries;
import util.HttpRequest;
import util.IRequest;
import util.WeatherPredicate;
import util.queries.LazyQueries;
import weather.WeatherWebApi;
import weather.model.Location;
import weather.model.WeatherInfo;

import java.time.LocalDate;
import java.util.Comparator;
import java.util.function.Function;

import static java.lang.System.out;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        IRequest req = new HttpRequest(); // new FileRequest();
        Function<String, Iterable<String>> logger = path -> () -> {
            System.out.println("Requesting...");
            return req.getContent(path).iterator();
        };
        // WeatherWebApi api = new WeatherWebApi(path -> logger.apply(path));
        WeatherWebApi api = new WeatherWebApi(logger::apply);
        System.out.println("Searching...");
        Iterable<Location> locals = api.search("oporto");
        System.out.println("Filtering...");
        LazyQueries.filter(locals, l -> l.getLatitude() > 0);
        // locals.forEach(System.out::println);
    }
}

